# Generated by Django 5.2.3 on 2025-07-08 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptitem",
            name="owners",
            field=models.ManyToManyField(
                related_name="owners", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
