# Generated by Django 5.2.3 on 2025-07-08 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_receiptitem_owners"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="owners",
            field=models.ManyToManyField(
                blank=True, related_name="owners", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
