# Generated by Django 5.2.3 on 2025-07-09 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_receipt_event_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="tips_percentage",
        ),
        migrations.RemoveField(
            model_name="event",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="eventgroup",
            name="description",
        ),
        migrations.AddField(
            model_name="event",
            name="tips",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Чаевые"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Сумма",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Общая сумма",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано в"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.eventgroup",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="invite_token",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Код приглашения",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Название мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Огранизатор мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="qr_raw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Сырой чек"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="receipt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="events.receipt",
                verbose_name="Чек",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="receipt_image",
            field=models.ImageField(
                upload_to="receipts", verbose_name="Фото чека"
            ),
        ),
        migrations.AlterField(
            model_name="eventgroup",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Название группы"
            ),
        ),
        migrations.AlterField(
            model_name="eventgroup",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="items",
            field=models.ManyToManyField(
                to="events.receiptitem", verbose_name="Позиции"
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="events.event",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                related_name="owners",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец позиции",
            ),
        ),
    ]
