# Generated by Django 5.2.3 on 2025-07-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_event_tips_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="qr_raw",
        ),
        migrations.RemoveField(
            model_name="event",
            name="receipt_image",
        ),
        migrations.RemoveField(
            model_name="event",
            name="total",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="total",
        ),
        migrations.AddField(
            model_name="receipt",
            name="qr_raw",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Сырой чек"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="items",
            field=models.ManyToManyField(
                blank=True, to="events.receiptitem", verbose_name="Позиции"
            ),
        ),
    ]
