# Generated by Django 5.2.3 on 2025-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0007_remove_event_qr_raw_remove_event_receipt_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="total",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Общая сумма",
            ),
        ),
    ]
