# Generated by Django 5.2.3 on 2025-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_receipt_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="receipt_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото чека"
            ),
        ),
    ]
